name: db_course_mobile
description: A lab for DB course

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+2
  rxdart: ^0.22.6
  provider: ^3.1.0+1
  shared_preferences: ^0.5.4+5


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
